### ISSUE TITLE
Possibly Misleading Definition of 'Minimal Hitting Set'

### ISSUE THREAD

**Issue by 7enderhead** [bdesham/hitting-set#1]
- your definition of 'minimal hitting set' seems to be 'a hitting set with minimal cardinality'
- but the literature defines a hitting set as minimal iff it has no proper subset that is also a hitting set
- e.g., R. Reiter, A Theory of Diagnosis from First Principles, definition 4.3:

> [...]
> A hitting set for _C_ is _minimal_ iff no proper subset of it is a hitting set for _C_.
- therefore, I suggest to rename `minimal-hitting-sets` to `minimal-cardinality-hitting-sets`
- minimal hitting sets according to the definition given above can be then computed as follows:

``` clojure
(defn minimal-hitting-sets [h]
  (let [hitting-sets (enumerate-hitting-sets h)]
    (filter
      (fn [hs]
        (let [others (disj hitting-sets hs)]
          (not-any? #(clojure.set/subset? % s) others)))
     hitting-sets)))
```

**Comment by bdesham** [comment]
I’m not an expert in this area but I don’t understand how the two definitions of “minimal hitting set,”
1. “a hitting set with minimal cardinality” and
2. “a hitting set with no proper subset that is also a hitting set,”

are different. Can you please clarify that for me?

**Comment by 7enderhead** [comment]
Here is an example: The minimum hitting sets for `{ {M1, M2, A1}, {M1, A1, A2, M3} }` are `{M1}`, `{A1}`, `{M2, A2}` and `{M2, M3}`.

Let's look at `{M2, A2}`: if we removed one element, it would not be a hitting set anymore (because its intersection with one of the input sets would be empty). So it is _minimal_ according to my definition: we cannot remove elements and still have a hitting set. But it has cardinality 2, and thus a higher cardinality than `{M1}` and `{A1}` (which are 'hitting sets with minimal cardinality' (1 in this case) according to our definition).

The important notion is that a 'minimal hitting set' does not necessarily have a minimum number of elements when compared to other (possibly non-minimal) hitting sets.

[This presentation](http://vc.cs.nthu.edu.tw/home/paper/codfiles/jwhuang/200708201524/K-Coverage960820.ppt) has the example.

**Comment by bdesham** [comment]
Ah, that makes sense. Thanks for the clarification! I’m traveling at the moment but I’ll revisit this in a week or so.

**Comment by bdesham** [comment]
It took a little longer than I thought but I finally got around to addressing this 🙂

**Comment by 7enderhead** [comment]
Cool!
